# Generated by Django 5.2.11 on 2026-06-14 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customeruser_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeruser',
            name='teacher',
            field=models.BooleanField(default=False, verbose_name='Вы хотите иметь возможность создавать комнаты(будеты выслан код подтверждения на вашу почту)?'),
        ),
    ]
