# Generated by Django 5.2.11 on 2026-06-09 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatting', '0002_answer_room_alter_answer_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='task',
        ),
        migrations.AddField(
            model_name='room',
            name='category',
            field=models.CharField(default=None),
        ),
        migrations.AddField(
            model_name='room',
            name='question',
            field=models.URLField(default=None),
        ),
        migrations.AlterField(
            model_name='room',
            name='title',
            field=models.CharField(),
        ),
    ]
