# Generated by Django 5.2.11 on 2026-06-09 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatting', '0003_remove_room_task_room_category_room_question_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='category',
            field=models.CharField(default='Art'),
        ),
        migrations.AlterField(
            model_name='room',
            name='question',
            field=models.URLField(default='https://opentdb.com/api.php?amount=1&category=25&difficulty=easy'),
        ),
    ]
