# Generated by Django 5.2.11 on 2026-06-09 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatting', '0004_alter_room_category_alter_room_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='category',
            field=models.BigIntegerField(),
        ),
    ]
