# Generated by Django 5.2.11 on 2026-06-11 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatting', '0006_remove_answer_answer_remove_answer_teacher_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='total_count',
            field=models.IntegerField(default=0),
        ),
    ]
