# Generated by Django 5.2.11 on 2026-06-12 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatting', '0007_answer_total_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='category',
            field=models.CharField(default=None),
        ),
        migrations.AddField(
            model_name='room',
            name='dificulty',
            field=models.CharField(default='easy'),
        ),
    ]
