# Generated by Django 5.2.11 on 2026-06-12 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatting', '0008_room_category_room_dificulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='category',
            field=models.CharField(default='Art'),
        ),
    ]
