# Generated by Django 5.2.11 on 2026-06-12 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatting', '0009_alter_room_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='category',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='dificulty',
            field=models.CharField(blank=True, null=True),
        ),
    ]
